name: tests-orders

on:
  push:
    branches: [ main ]
    paths:
      - 'orders/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
