name: tests-payments

on:
  push:
    branches: [ main ]
    paths:
      - 'payments/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
